### ISSUE TITLE
Feature request, animation direction toggle

### ISSUE THREAD

**Issue by Ghostypunchy** [RoyRiv3r/notifications-anywhere#1]
would it be possible to have a toggle to change the notification animation to appear from left to right, instead from right to left? 

when moving the notification to the left side of the screen, the notifications seemingly appear out of thin air and it looks weird. it woulld be good if we could choose to change the animation direction of it.

**Comment by RoyRiv3r** [comment]
Hi, unfortunately, due to limitations with the Windows notification API, we are unable to achieve that to my knowledge. A workaround would be to develop a custom notification application that replaces the existing Windows notification system entirely with that effect. Sorry :/

**Comment by Ghostypunchy** [comment]
got it. no worries at all and thank you for the reply! 

and now on an unrelated note, do you happen to maybe still have the original builder file for the application that SamarthCat had released?

**Comment by RoyRiv3r** [comment]
I think this is the one, i'm not sure, it's been a while and for some reason SamarthCat removed the repo
[notifications-at-top-1.1.0.zip](https://github.com/RoyRiv3r/notifications-anywhere/files/14964351/notifications-at-top-1.1.0.zip)
