### ISSUE TITLE
Just An Explanation

### ISSUE THREAD

**Issue by SamarthMP** [RoyRiv3r/notifications-anywhere#2]
Hey There!
It's me, SamarthCat (I changed my GitHub name, hence the original repo being gone)
I just wanted to inform RoyRiv3r and anyone who still needs the upstream code that the new repo can be found [here](https://github.com/SamsidParty/TopNotify). It is has a new program architecture but still uses the same logic for notification positioning.

**Comment by RoyRiv3r** [comment]
Hi. Thanks for the update. I've included the link to this project in my readme!

**Comment by SamarthMP** [comment]
Great! Btw, this repo should be licensed under GPL v3. Mainly because I don't want a massive company to take the code and make a rip-off. It would be nice if you changed the license to GPL, but it's up to you since the original repo had no license.

**Comment by RoyRiv3r** [comment]
Sure I can do that.

**Comment by SamarthMP** [comment]
Thanks, Good luck with your project, and feel free to use any upstream code or contribute to the new repo if you want. I am closing this issue now.
