### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by tapochek666** [RoyRiv3r/notifications-anywhere#3]
Strange. When I start the program, I get an error.
![Буфер обмена01](https://github.com/RoyRiv3r/notifications-anywhere/assets/164499068/c4f1791f-b54b-4b66-8d1b-3af177ce2480)

**Comment by RoyRiv3r** [comment]
Should work now, let me know if there is still issue.

**Comment by tapochek666** [comment]
After fixing everything works. 👍

**Comment by tapochek666** [comment]
I'm so sorry. Is it possible to set up the appearance animation so that you
can choose which side the notifications will pop up from? For example, if I
set the notification to the left, then the appearance animation will be
from left to right.

чт, 18 апр. 2024 г. в 07:29, RoyRiver ***@***.***>:

**Comment by RoyRiv3r** [comment]
Hi, unfortunately no, like explained here #1, the limitation of windows prevent us from doing that, the notification isn't supposed to be elsewhere in the first place so this is a 'hack' that moves the notification window, unless Microsoft decide to implement the animation or someone have to make an entire custom notification there is no solution sorry.

**Comment by tapochek666** [comment]
Хорошо, спасибо за ответ.

вс, 28 апр. 2024 г. в 18:40, RoyRiver ***@***.***>:
