### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by tapochek666** [RoyRiv3r/notifications-anywhere#7]
Hello.Tested releases 1.4 and 1.5... It’s no longer possible to set the position close to the edges (right-left) and it’s impossible to move notifications to the very top of the screen as it was in version 1.2. :(

**Comment by RoyRiv3r** [comment]
Check the new update, tell me if it's working now, otherwise you might check other more modern approach project doing the same goal: <a href="https://github.com/SamsidParty/TopNotify">TopNotify</a>

**Comment by tapochek666** [comment]
Now the notification moves normally, as in version 1.2. Another question: in which line should I move the “Enable Click Through Notification” checkbox? It’s too close to the edge of the options menu. Thank you!

**Comment by RoyRiv3r** [comment]
> Another question: in which line should I move the “Enable Click Through Notification” checkbox? It’s too close to the edge of the options menu. Thank you!

Sorry, I don't understand your question, the Click through should work, at least it's working on my side

**Comment by tapochek666** [comment]
I'm talking about the checkbox itself. It would be nice to move it a little to the right...
![Буфер обмена_05-14-2024_01](https://github.com/RoyRiv3r/notifications-anywhere/assets/164499068/48498ef7-b08a-4f91-9ead-6a433a87aee6)

**Comment by RoyRiv3r** [comment]
Oh i see, you’re talking about the design not center. let me see if I can change that

**Comment by tapochek666** [comment]
Now everything is great!
